//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimetableDTO", Namespace="http://schemas.datacontract.org/2004/07/ServiceTimeTable.EntitryDto")]
    public partial class TimetableDTO : object
    {
        
        private System.Nullable<int> CountHoursLectureField;
        
        private System.Nullable<System.DateTime> DateSubjectField;
        
        private string DaySubjectField;
        
        private string GroupNameField;
        
        private string LinkLectureField;
        
        private string NameSessionsField;
        
        private string NameTeacherField;
        
        private string NumberCabinetField;
        
        private System.Nullable<int> NumberLectureField;
        
        private System.Nullable<int> NumberWeekField;
        
        private System.Nullable<int> SubGroupNumberField;
        
        private string SubjectField;
        
        private string TimeLectureField;
        
        private string TypeLectureField;
        
        private System.Nullable<System.DateTime> YearSessionsField;
        
        private int idCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CountHoursLecture
        {
            get
            {
                return this.CountHoursLectureField;
            }
            set
            {
                this.CountHoursLectureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSubject
        {
            get
            {
                return this.DateSubjectField;
            }
            set
            {
                this.DateSubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DaySubject
        {
            get
            {
                return this.DaySubjectField;
            }
            set
            {
                this.DaySubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                this.GroupNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkLecture
        {
            get
            {
                return this.LinkLectureField;
            }
            set
            {
                this.LinkLectureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameSessions
        {
            get
            {
                return this.NameSessionsField;
            }
            set
            {
                this.NameSessionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameTeacher
        {
            get
            {
                return this.NameTeacherField;
            }
            set
            {
                this.NameTeacherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberCabinet
        {
            get
            {
                return this.NumberCabinetField;
            }
            set
            {
                this.NumberCabinetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberLecture
        {
            get
            {
                return this.NumberLectureField;
            }
            set
            {
                this.NumberLectureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberWeek
        {
            get
            {
                return this.NumberWeekField;
            }
            set
            {
                this.NumberWeekField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SubGroupNumber
        {
            get
            {
                return this.SubGroupNumberField;
            }
            set
            {
                this.SubGroupNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeLecture
        {
            get
            {
                return this.TimeLectureField;
            }
            set
            {
                this.TimeLectureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeLecture
        {
            get
            {
                return this.TypeLectureField;
            }
            set
            {
                this.TypeLectureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> YearSessions
        {
            get
            {
                return this.YearSessionsField;
            }
            set
            {
                this.YearSessionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCount
        {
            get
            {
                return this.idCountField;
            }
            set
            {
                this.idCountField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWebSiteService")]
    public interface IWebSiteService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebSiteService/GetTimetableFR", ReplyAction="http://tempuri.org/IWebSiteService/GetTimetableFRResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.TimetableDTO>> GetTimetableFRAsync(string nameGroup);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IWebSiteServiceChannel : ServiceReference1.IWebSiteService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebSiteServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IWebSiteService>, ServiceReference1.IWebSiteService
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebSiteServiceClient() : 
                base(WebSiteServiceClient.GetDefaultBinding(), WebSiteServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWebSiteService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebSiteServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WebSiteServiceClient.GetBindingForEndpoint(endpointConfiguration), WebSiteServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebSiteServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebSiteServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebSiteServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebSiteServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebSiteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ServiceReference1.TimetableDTO>> GetTimetableFRAsync(string nameGroup)
        {
            return base.Channel.GetTimetableFRAsync(nameGroup);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWebSiteService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWebSiteService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.0.200:8733/Design_Time_Addresses/ServiceTimeTable/WebSiteService/");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WebSiteServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWebSiteService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WebSiteServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWebSiteService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWebSiteService,
        }
    }
}
